export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ALL_LEVELS_BEGIN = "GET_ALL_LEVELS_BEGIN";
export const GET_ALL_LEVELS_SUCCESS = "GET_ALL_LEVELS_SUCCESS";
export const GET_ALL_LEVELS_FAIL = "GET_ALL_LEVELS_FAIL";

export const GET_SINGLE_LEVEL_BEGIN = "GET_SINGLE_LEVEL_BEGIN";
export const GET_SINGLE_LEVEL_SUCCESS = "GET_SINGLE_LEVEL_SUCCESS";
export const GET_SINGLE_LEVEL_FAIL = "GET_SINGLE_LEVEL_FAIL";

export const SAVE_PROGRESS = "SAVE_PROGRESS";
export const LANGUAGE_TOGGLE = "LANGUAGE_TOGGLE";
export const THEME_TOGGLE = "THEME_TOGGLE";
export const MY_LEVEL_BEGIN = "MY_LEVEL_BEGIN";
export const MY_LEVEL_SUCCESS = "MY_LEVEL_SUCCESS";
export const MY_LEVEL_FAIL = "MY_LEVEL_FAIL";
